### PR TITLE
Finaltouch Style

### PR DESCRIPTION
**Pull request by osamaashraf6**
## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Set up a new project with webpack.
- [x] Add the final touch for CSS 👌.   
- [x] Use the API for post and get data from and to API. 
- [x] Add the functionality for the submit and refresh btns for POST and GET data from to API 👍  
- [x] Create an index.html file and write my HTML markup here. 
- [x] Create The index.html file by setting it as a template using the HTML Webpack Plugin.💯
- [x] Create a style.css and set rules for the LeaderBoard. CSS loaded by Webpack Style/CSS Loader.
- [x] Use GitFlow in the project.

## Description of the task to be completed 👎 

- HTML
- CSS
- Flexbox
- Set up the project using webpack.

  
## How should it be tested

Clone the repository
```
git clone https://github.com/osamaashraf6/Leaderboard.git
```
Navigate to the folder
```
cd Leaderboard
```
Checkout the branch
```
git checkout finaltouch__style
```

### CODE REVIEW

**Review by Bondok6 — CHANGES_REQUESTED** [review]
## Hi @osamaashraf6 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No Linter errors ✅
- Correct GitHub flow ✅
- Your repo is professional ✅
- App is properly styled well ✅


## Required Changes ♻️

- [ ] Your README file is well documented, but I noticed that the MIT link in your README is broken so I suggest to fix it by changing the path from `[MIT](./LICENSE)` to `[MIT](./MIT.md)`👍
- [ ] Also, I suggest removing this `NOTE ...` recommendation from your README file 💯



- [ ] Great job adding the MIT.md file, but you forgot to customize it, So I suggest adding your name and customizing it 👍

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Santiago220991 — APPROVED** [review]
Hi @osamaashraf6, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
:heavy_check_mark: Applied changes suggested by the last reviewer.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Followed GitFlow.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by osamaashraf6** [comment]
- Thanks 🙏 for reviewing my pull request  I appreciate your review 💯 
### Thanks for reviewing my PR 😊

**Comment by osamaashraf6** [comment]
- Thanks 🙏 for reviewing my pull request I appreciate your review 💯 
### Thanks again for reviewing my PR  and have a good day😊

**Pull request merged**
